### ISSUE TITLE
CLI tool?

### ISSUE THREAD

**Issue by piranna** [npmgraph/npmgraph#149] opened 2023-09-24 05:53 UTC
Is there any way to use this as a headless CLI tool? Provide a `package.json` file as argument, and get the SVG content in stdout.

**Comment by piranna** [comment] 2023-09-24 06:05
Is being done the rendering server side? If so, it could be done with just a single `fetch()` request...

**Comment by broofa** [comment] 2023-09-30 09:41
This is not something I've designed for so, no, there's no simple way to render graphs on the server at the moment.

It might be possible to generate graphs with `puppeteer`, but I haven't explored that.

The core SVG  is created by generating a [DOT document](https://graphviz.org/doc/info/lang.html) and running that through graphviz.  So another option would be to write a script to do something similar and then call into one of the many availalbe language [APIs for graphviz](https://graphviz.org/resources/#language-bindings) to generate the diagram.  But NPMGraph also does direct DOM manipulation of the SVG graph for selection, colorizing, and other other view-related behavior, so this approach wouldn't capture those aspects of the graph.

**Comment by broofa** [comment] 2023-10-24 13:25
@piranna  Have you looked at https://www.npmjs.com/package/madge?   'Would be curious to hear your thoughts on how that tool does/doesn't overlap with what a headless `npmgraph` might provide.

**Comment by piranna** [comment] 2023-10-24 13:56
> @piranna Have you looked at [npmjs.com/package/madge](https://www.npmjs.com/package/madge)? 'Would be curious to hear your thoughts on how that tool does/doesn't overlap with what a headless `npmgraph` might provide.

Yes, in fact I'm using it :-) It generates the graph at modules level, not at packages level. For me it's useful to detect circular references in complex code bases that can lead to bugs.

**Comment by broofa** [comment] 2023-10-25 13:09
FWIW, I've just published the first version of [the `npmgraph` CLI](https://github.com/npmgraph/npmgraph-cli).  It's not what you're asking for here, but may still be of interest.  It's basically a fancy URL-opener for now.

**Comment by fregante** [comment] 2024-07-28 11:26
Duplicate of https://github.com/npmgraph/npmgraph-cli/issues/2

**Closed by fregante** 2024-07-28 11:26 UTC
