### ISSUE TITLE
Add a CLI script to locally generate the graph svg

### ISSUE THREAD

**Issue by matheusd** [npmgraph/npmgraph#87] opened 2021-06-14 13:00 UTC
The main use case would be to automate generation of the dependency graph without having to spin a browser and download the svg.

Ideally, this would be project-local script that would get installed as a dev dependency to be executed either manually or in a CI. The user API would be something like:

```
$ npmgraph --packages "foo,bar@1.3.4,baz" --output my-project-deps.svg
```

**Comment by broofa** [comment] 2021-06-14 22:20
Good idea.  'Shouldn't be that hard to get working.  Fetching the dependency tree happens in Store.js, which uses `window.fetch()` under the hood.  That would have to be refactored to work on the server.  Also, getting `graphviz` to run on the server will take a similar rework.

People will probably want this to work with local filesystem repos, github repos, and private registries, though... that's a whole other bag of worms to deal with.

**Comment by fregante** [comment] 2024-07-28 11:24
Duplicate of https://github.com/npmgraph/npmgraph/issues/149

**Closed by fregante** 2024-07-28 11:24 UTC
Labels: help wanted
